#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
rm *.sh
apt install unzip -y && wget github.com/nandoslayer/plusnssh/raw/ntech/gestorssh/sincpainel.zip && unzip sincpainel.zip && chmod 777 *sh && rm sincpainel.zip > /dev/null 2>&1
service ssh restart
echo -e "\n\033[1;32mCONCLUIDO!\033[0m"
sleep 1.5
cat /dev/null > ~/.bash_history && history -c && clear
echo -e "\033[1;36mENTRE NO PAINEL E CRIE UMA CONTA SSH PRA VER SE ESTA TUDO OK!\033[0m"
rm inst sincpainel.zip > /dev/null 2>&1
